// Generated from verified local OpenAI recordings. No runtime API calls.
export const recordedVoices: Record<string, string> = {
  "Su|เกี่ยวกับกรุงเทพครับ": "/bangkok/voices/about-bangkok.mp3",
  "Su|กินหลังอาหารใช่ไหมครับ": "/bangkok/voices/after-food.mp3",
  "Su|ห้องน้ำอยู่ที่ไหนครับ": "/bangkok/voices/bathroom-where.mp3",
  "Su|คิดเงินด้วยครับ": "/bangkok/voices/bill-please.mp3",
  "Su|ซื้อสองชิ้นลดได้ไหมครับ": "/bangkok/voices/buy-two.mp3",
  "Su|ช่วยโทรหาตำรวจให้หน่อยครับ": "/bangkok/voices/call-police.mp3",
  "Su|ขอดูได้ไหมครับ": "/bangkok/voices/can-see.mp3",
  "Su|ขอเช็กอินครับ": "/bangkok/voices/check-in-please.mp3",
  "Su|อร่อยมากครับ": "/bangkok/voices/delicious.mp3",
  "Su|ลดราคาได้ไหมครับ": "/bangkok/voices/discount.mp3",
  "Su|ลิฟต์อยู่ที่ไหนครับ": "/bangkok/voices/elevator-where.mp3",
  "Su|ดีขึ้นแล้วครับ": "/bangkok/voices/feel-better.mp3",
  "Su|มีไข้ครับ": "/bangkok/voices/fever.mp3",
  "Su|เย็นนี้ว่างครับ": "/bangkok/voices/free-evening.mp3",
  "Su|ว่างเมื่อไหร่ครับ": "/bangkok/voices/free-when.mp3",
  "Su|เพื่อนผมหายครับ": "/bangkok/voices/friend-missing.mp3",
  "Su|ไปโรงแรมนี้ครับ": "/bangkok/voices/go-hotel.mp3",
  "Su|ไปยังไงครับ": "/bangkok/voices/go-how.mp3",
  "Su|ตรงไปครับ": "/bangkok/voices/go-straight.mp3",
  "Su|ไปวัดนี้ครับ": "/bangkok/voices/go-to-shrine.mp3",
  "Su|ไปด้วยกันไหมครับ": "/bangkok/voices/go-together.mp3",
  "Su|มีสีอื่นไหมครับ": "/bangkok/voices/has-color.mp3",
  "Su|ผมแพ้ยานี้ครับ": "/bangkok/voices/have-allergy.mp3",
  "Su|ปวดหัวครับ": "/bangkok/voices/headache.mp3",
  "Su|สวัสดีครับ": "/bangkok/voices/hello.mp3",
  "Su|ใช้เวลานานแค่ไหนครับ": "/bangkok/voices/how-long.mp3",
  "Su|กินวันละกี่ครั้งครับ": "/bangkok/voices/how-many-times.mp3",
  "Su|ราคาเท่าไหร่ครับ": "/bangkok/voices/how-much.mp3",
  "Su|ไปที่นั่นเท่าไหร่ครับ": "/bangkok/voices/how-much-to-go.mp3",
  "Su|ผมหลงทางครับ": "/bangkok/voices/i-am-lost.mp3",
  "Su|ผมหิวน้ำครับ": "/bangkok/voices/i-am-thirsty.mp3",
  "Su|เข้าใจแล้วครับ": "/bangkok/voices/i-understand.mp3",
  "Su|ผมเอาอันนี้ครับ": "/bangkok/voices/i-will-buy.mp3",
  "Su|เรื่องนี้สำคัญครับ": "/bangkok/voices/important-matter.mp3",
  "Su|กุญแจอยู่ที่ไหนครับ": "/bangkok/voices/key-where.mp3",
  "Su|ผมชอบกาแฟครับ": "/bangkok/voices/like-coffee.mp3",
  "Su|ผมชอบอาหารไทยครับ": "/bangkok/voices/like-thai-food.mp3",
  "Pim|The lakeside is quiet again. Pim sets a flask on the bench. “People have started walking here in the evening. You helped give the park back to them.”": "/bangkok/voices/line-007dc34f5076cc18.mp3",
  "Su|Su writes your introduction beneath the other travellers. A small envelope inside is marked “For your first city day.”": "/bangkok/voices/line-00c0e7e0db1c9354.mp3",
  "Uncle Lek|Lek puts the chilli jar away. “Mild, for both of you.”": "/bangkok/voices/line-024eca6e10f867f8.mp3",
  "Su|“Then Yaowarat it is,” Su says. “Let us find a meal we can sit down for.”": "/bangkok/voices/line-027b84b78855f7a8.mp3",
  "Su|A new page for our explorer’s journal. You found 2 of 6 city memories. Find all six to earn the River Charm: it restores 15 HP after each story battle victory.": "/bangkok/voices/line-0377add2885442ca.mp3",
  "Su|Think of the people who helped us today. This is a goodbye with a promise to return. Practise telling them you will see them again.": "/bangkok/voices/line-04cb965739c0cb4b.mp3",
  "Su|Talk to Su. Find out where the rift brought you. Look around, open your map, or talk to people again. If you want to rehearse a phrase, we can train at camp.": "/bangkok/voices/line-05283489dbaf4506.mp3",
  "Su|An evening meal in Yaowarat is your plan. Invite Mali at the Sukhumvit hotel. Look around, open your map, or talk to people again. If you want to rehearse a phrase, we can train at camp.": "/bangkok/voices/line-0802dbad7b02a107.mp3",
  "Mali|Mali looks from the guest book to you. “Niran actually picked a time? That is a first.” You explain the evening meal at Lek’s stall. She hesitates over the desk bell, then turns the guest book toward her colleague. “Ask me properly. I have been waiting for an excuse to leave this chair.” Invite her to go together.": "/bangkok/voices/line-081f30dec0e294fc.mp3",
  "Su|Blue shutters beside a tree. Before handing over a sealed letter, let us check the route notice and make sure this is the intended house.": "/bangkok/voices/line-0871519bdb9c0645.mp3",
  "Su|An unfinished lantern reveals the frame beneath its paper. Arun has left sample pieces for visitors to handle. Su smiles: “You do not need to know every word. A good question is enough to begin.”": "/bangkok/voices/line-0c42aff208521e8b.mp3",
  "Su|A new page for our explorer’s journal. You found 6 of 6 city memories. Together, these memories form a River Charm. After a story battle victory, it restores 15 HP.": "/bangkok/voices/line-0db8bea5439daa61.mp3",
  "Dao|Dao points along the viaduct. “You found it. Follow the station signs from here.” Nok lets out a relieved breath.": "/bangkok/voices/line-0dc6c5ce78ff7cb9.mp3",
  "Su|You recovered the ferry ledger. Kanya’s archive now remembers Patrick and Su beside the people who first lit the river path. Look around, open your map, or talk to people again. If you want to rehearse a phrase, we can train at camp.": "/bangkok/voices/line-0dd12e4be1e2077f.mp3",
  "Pim|She gives you a folded paper shade. “That lamp was my father’s idea. He used to walk this way after closing his stall.” Thank her for helping.": "/bangkok/voices/line-0e55b33aea155182.mp3",
  "Su|Behind the main street, a shopkeeper has drawn a tiny map. A train runs across its top; below it are a tailor, a food cart and a dog asleep in the shade. The route makes sense once you know what to ask.": "/bangkok/voices/line-0eb31ae182758dbd.mp3",
  "Kanya|Kanya opens the ledger. “My grandfather carried paper lanterns on the last ferry. People left them burning for neighbours walking home.” She gives you a copy of the route and tea for your journey. Thank her for her time.": "/bangkok/voices/line-0ec3670b44498190.mp3",
  "Nok|Nok smiles. “Yes, please. Lead the way. I will stay close.”": "/bangkok/voices/line-10cf356a643deb35.mp3",
  "Su|A carved wooden boat sits on a low plinth. Niran’s note says his daughter made it before she moved across the city. Under the hull she wrote a promise to visit. Su asks you to practise a goodbye that leaves the door open.": "/bangkok/voices/line-1129d51ebb9df1f0.mp3",
  "Su|The spark we recovered answers the lantern, but the Keeper still holds the river passage shut. Everything we brought through the city matters here: our word arts, our talents, and the food our neighbours packed.": "/bangkok/voices/line-113a61893b8d8b62.mp3",
  "Suda|The letter is delivered. The neighbours are planting a canal garden today. Ask at the garden boat on the near quay if you would like to help with the flower deliveries. The ferry remains available whenever you want to return.": "/bangkok/voices/line-11a86c99c15289e8.mp3",
  "Su|The arrows point steadily now. Your Wayfinder Seal starts every future battle with 20 resonance. The main road is yours again.": "/bangkok/voices/line-13bc97803b948cb8.mp3",
  "Uncle Lek|Lek measures a small spoonful. “Just a little. Water is right here.”": "/bangkok/voices/line-142698370142e08c.mp3",
  "Kanya|“The ferry deliveries. Of course.” Kanya finds the key to the original collection. The archive belongs to everyone, but these old pages are fragile. Ask to see the document before she opens it.": "/bangkok/voices/line-157910df44667164.mp3",
  "Su|You chose Pim’s tea beside the Lumphini lake. Su remembers the warm flask between you and the lights reflected in the water.": "/bangkok/voices/line-16391bafbcabfe23.mp3",
  "Su|Invite Nok to walk with us. You know where Dao stands, and two travellers can find their way together.": "/bangkok/voices/line-166dfa96ce56f4a5.mp3",
  "Su|A new page for our explorer’s journal. You found 3 of 6 city memories. Find all six to earn the River Charm: it restores 15 HP after each story battle victory.": "/bangkok/voices/line-1769644da7081a53.mp3",
  "Mali|There is a reservation here with your name on it. Tell me you have a booking.": "/bangkok/voices/line-17c0ead98f4475b1.mp3",
  "Su|Help the boat tender deliver flowers to the coloured quays in any order. 0 of 3 trays delivered. Look around, open your map, or talk to people again. If you want to rehearse a phrase, we can train at camp.": "/bangkok/voices/line-19b22ee990871d3d.mp3",
  "Dao|Nok reaches the train viaduct beside you. Before pointing the way, check with Dao: where is the station?": "/bangkok/voices/line-1c53c712a5f3d7f9.mp3",
  "Mali|Mali looks up from the guest book. “There you are, Patrick. Your room is ready. No charge—you have already checked in.”": "/bangkok/voices/line-1fc9d336f74651b0.mp3",
  "Niran|The lantern is out, the river is full of mist, and I have not eaten since morning. Could you ask Uncle Lek in Yaowarat about my supper?": "/bangkok/voices/line-1febdcca61076085.mp3",
  "Su|“See you.” The words feel different beside the river. You leave the little boat where it belongs and accept the tea Niran has set out for visitors.": "/bangkok/voices/line-20543954b5cc15a3.mp3",
  "Su|These shutters are red, and the letter is addressed to the blue-shutter house across the water. Keep it sealed. Look for the narrow footbridge along this quay.": "/bangkok/voices/line-20b8a109a24ac7ba.mp3",
  "Su|We have identified the collection. Kanya keeps the key to the originals. Let us return to reception and ask her to show us the ledger.": "/bangkok/voices/line-2388145466e7efae.mp3",
  "Niran|Take this ferry pass. Restore the light and I will get you across. Thank him.": "/bangkok/voices/line-24b2087b3bcf64c7.mp3",
  "Su|“Any time, Patrick.” Warm light spreads over the canal rail. A note from Pim waits beneath it: “For our two new neighbours.”": "/bangkok/voices/line-26029c7f6ef2b08c.mp3",
  "Su|Explore the reading room and both galleries. 1 of 3 clues recorded; the rooms connect around a shaded courtyard. Look around, open your map, or talk to people again. If you want to rehearse a phrase, we can train at camp.": "/bangkok/voices/line-269aba486cf00969.mp3",
  "Su|The canal lantern shines again. Pim and Arun both helped you leave the path brighter.": "/bangkok/voices/line-26b267a9c737fdce.mp3",
  "Su|You practise the request. Beneath the drinking water is a sealed flask of Thai tea, left for the next tired traveller. You tuck it into your bag.": "/bangkok/voices/line-2714dd0ca5dbaea7.mp3",
  "Su|The arrows settle. A brass compass opens and the Waywarden answers your call.": "/bangkok/voices/line-27389700ad9ccda8.mp3",
  "Su|Collect paper from Pim in Lumphini and a frame from Arun in Old Town. Visit them in either order, then return to the canal lantern.": "/bangkok/voices/line-2881c18cccdebdf6.mp3",
  "Su|An old recipe board carries three generations of handwritten changes. A small serving is set aside for a traveller. Su points to the chilli jar: “Make the meal yours. Tell the cook how you want it.”": "/bangkok/voices/line-2894b4841022c4bd.mp3",
  "Uncle Lek|“Niran sent the empty bowl back,” Lek says, laughing. “That is his way of saying it was good. Shall I pack something for your next walk?”": "/bangkok/voices/line-291a2a6f275b4a9f.mp3",
  "Su|Let us check in at the hotel first. Then we can ask the archivist about exploring these rooms.": "/bangkok/voices/line-2aff8155e9f69289.mp3",
  "Su|The bow turns right. The next straight instruction follows this new heading.": "/bangkok/voices/line-2b0afb5a163d437d.mp3",
  "Arun|“Go carefully, Patrick. Words—and people—deserve patience.”": "/bangkok/voices/line-2b480a69326a1c2c.mp3",
  "Arun|“Twenty-four, then. I made the carving myself, so that is my best price.” Arun smiles. You can accept his offer, ask about something within your budget, or leave.": "/bangkok/voices/line-2bf0851aed4fc02d.mp3",
  "Su|Tomorrow at the Lumphini pavilion is your plan. Invite Arun at his Old Town workshop. Look around, open your map, or talk to people again. If you want to rehearse a phrase, we can train at camp.": "/bangkok/voices/line-2c9356d33aca5c57.mp3",
  "Su|Suda’s neighbours have shared three trays of marigolds. Help the boat tender take them to the red, blue and green quays in any order. Face the direction you want, then go straight to the next channel marker. Floating planters block the middle of the near lane. Ask to stop beside a coloured quay to unload. Nobody is in a hurry.": "/bangkok/voices/line-2e1b83b7424caeff.mp3",
  "Su|Every arrow points somewhere different. Instead of guessing, ask where you want to go. Say that you are looking for the station.": "/bangkok/voices/line-2e62cd6ad079797f.mp3",
  "Su|Follow the quay left from this landing. At the red-shutter house, take the narrow bridge across the canal. On the far quay, turn right. The blue shutters are beside a tree. Keep the letter sealed.": "/bangkok/voices/line-306ac800b085acb5.mp3",
  "Pim|Take a breath. Lumphini is a quiet pocket of trees and water inside a busy city. Are you thirsty after that walk?": "/bangkok/voices/line-30b4af715ae2d147.mp3",
  "Su|You brought Mali, Arun and Niran together for an evening meal in Yaowarat. Mali and Arun now have plans for a lantern at the hotel. You made a place for yourself at their table. Look around, open your map, or talk to people again. If you want to rehearse a phrase, we can train at camp.": "/bangkok/voices/line-30cd4ea72f88b12f.mp3",
  "Su|Help the boat tender deliver flowers to the coloured quays in any order. 2 of 3 trays delivered. Look around, open your map, or talk to people again. If you want to rehearse a phrase, we can train at camp.": "/bangkok/voices/line-31c6c421b4a19f9b.mp3",
  "Su|The tender is ready. Turn the bow, then go straight to the next marker. Ask to stop at a coloured quay. You can open the channel chart whenever you need it.": "/bangkok/voices/line-32cbef20c4233d90.mp3",
  "Su|Su follows your question with her finger, tracing the way to Dao. On the board, a note offers a few coins to travellers who help keep these small routes remembered.": "/bangkok/voices/line-33f2a854ef119527.mp3",
  "Mali|“Tomorrow morning? I finish the night shift at seven.” Mali closes the guest book. “Usually I go straight home. I cannot remember the last time I sat beside the lake.” You tell her Niran is making time too. Invite her to go together; she can meet you at Pim’s pavilion after her shift.": "/bangkok/voices/line-34213990079dbe5d.mp3",
  "Suda|Suda accepts the sealed letter. She recognises the handwriting and smiles. “My sister says she will visit. It has been a long time.”": "/bangkok/voices/line-34c16393b9e23955.mp3",
  "Pim|Pim slows down and demonstrates one fold at a time. “Keep the paper dry until Arun has checked the frame.”": "/bangkok/voices/line-39ae880eece04303.mp3",
  "Niran|Lek remembered! I was beginning to think I would spend the whole night here. He explains the broken lantern very quickly. Ask him to slow down.": "/bangkok/voices/line-3b1134d175fa75ff.mp3",
  "Su|This quay already has its flowers. The tender waits for your next direction.": "/bangkok/voices/line-3b67991a4b652e50.mp3",
  "Su|The tray is unloaded and the neighbours plant their flowers. Choose another coloured quay for the remaining trays.": "/bangkok/voices/line-3b778b90e9041934.mp3",
  "Mali|“So this is yours!” Mali hands you an old brass key.": "/bangkok/voices/line-3c24e1a254d57d2e.mp3",
  "Niran|A boat horn swallows his last sentence. Ask him to say it again.": "/bangkok/voices/line-3cc9366d027c920c.mp3",
  "Su|Collect a frame from Arun in Old Town. Visit them in either order, then return to the canal lantern.": "/bangkok/voices/line-3f8619a404b6e589.mp3",
  "Su|The missing lantern spark is caught inside that spirit. We cannot restore the last ferry until we free it. Stay beside me, Patrick. This is our first fight together.": "/bangkok/voices/line-3f90d8e17c7bfdec.mp3",
  "Su|Pim opens the tea flask and pours for you both. Su watches the small ripples. “I kept thinking we had to hurry. I had forgotten we could choose to stop.” Thank Pim for making you welcome.": "/bangkok/voices/line-400f5195bf82961d.mp3",
  "Uncle Lek|Niran cannot handle much chilli. Tell me you want it not spicy.": "/bangkok/voices/line-42f0a6de2c57c452.mp3",
  "Mali|You leave the room rested. Mali has put fresh water beside the guest book.": "/bangkok/voices/line-43cdf1a697ae46c3.mp3",
  "Mali|Mali has heard about the river lantern. She leaves your key on the desk. “You have a home here now. Come back whenever you need to rest.”": "/bangkok/voices/line-453130220e27e0da.mp3",
  "Su|An evening meal in Yaowarat is your plan. Invite Mali at the hotel and Arun in Old Town, in either order. Look around, open your map, or talk to people again. If you want to rehearse a phrase, we can train at camp.": "/bangkok/voices/line-48918c38e26c451a.mp3",
  "Pim|Pim makes space beside the pavilion. “Water, or the tea in this flask?” She points to the flask so you can ask for “this one.” Su watches the reflections while you choose.": "/bangkok/voices/line-4ad6585f78702e00.mp3",
  "Su|The ferry brought you home. Return to Niran at the pier: he has a promise he has never quite managed to keep. Look around, open your map, or talk to people again. If you want to rehearse a phrase, we can train at camp.": "/bangkok/voices/line-4c4ac79f64b424ec.mp3",
  "Su|A new page for our explorer’s journal. You found 5 of 6 city memories. Find all six to earn the River Charm: it restores 15 HP after each story battle victory.": "/bangkok/voices/line-4cb0526d26e82e26.mp3",
  "Su|This is the narrow bridge from the notice. Look across the water: the blue shutters are on the far quay. Cross here, then follow the timber walk right. The red house on this side belongs to someone else.": "/bangkok/voices/line-4cc66455b9acd143.mp3",
  "Su|You bring the paper and frame together. Su holds the shade steady while you fit it over the lamp. Thank her for the extra pair of hands.": "/bangkok/voices/line-4d5b1e79b7687ca7.mp3",
  "Su|An evening meal in Yaowarat is your plan. Invite Arun at his Old Town workshop. Look around, open your map, or talk to people again. If you want to rehearse a phrase, we can train at camp.": "/bangkok/voices/line-51a24915302e2bea.mp3",
  "Su|Work out a river departure, ask your way through Sukhumvit, and return to your hotel.": "/bangkok/voices/line-530c9d0f46d674d2.mp3",
  "Su|Tomorrow at the Lumphini pavilion is your plan. Invite Mali at the Sukhumvit hotel. Look around, open your map, or talk to people again. If you want to rehearse a phrase, we can train at camp.": "/bangkok/voices/line-535cfe1da73329d7.mp3",
  "Su|You ask what it is made from. A workshop note explains the frame and covering, then invites you to take a small travel allowance for helping preserve the lantern trail.": "/bangkok/voices/line-5360c2e466d3981d.mp3",
  "Niran|Niran slows down and points: Lumphini spark, Old Town lantern, clear passage.": "/bangkok/voices/line-53696347580e9193.mp3",
  "Su|Tomorrow at the Lumphini pavilion is your plan. Invite Mali at the hotel and Arun in Old Town, in either order. Look around, open your map, or talk to people again. If you want to rehearse a phrase, we can train at camp.": "/bangkok/voices/line-545852c7bbea6238.mp3",
  "Su|The old chest is empty. Your Jade Ward is already equipped: it reduces every spirit hit by 3 HP.": "/bangkok/voices/line-56b20fe849a8fde1.mp3",
  "Uncle Lek|Lek sets the bowl on the counter. “Good choice.”": "/bangkok/voices/line-56dc9c5e36ed3e90.mp3",
  "Su|The tender rows to the next channel marker and waits for your next instruction.": "/bangkok/voices/line-576bf79512b05818.mp3",
  "Su|An optional challenge: compass armor halves word damage until exposed. Use Su’s Echo Lens, then Patrick’s Clear Intent. Counters and our duet bypass the armor. Heavy attacks come every second round; break or weaken it first. Win the Wayfinder Seal to start future battles with 20 resonance. We can leave and prepare first.": "/bangkok/voices/line-580b890842ee7538.mp3",
  "Arun|A little lantern hangs above Arun’s bench. “For the side paths,” he says. Su turns its carved frame in the light. Before deciding, find out what it costs.": "/bangkok/voices/line-5902181327647c9e.mp3",
  "Su|Break or weaken the Keeper before its heavy third-round attack. Its Echo can heal it; a parry interrupts that healing. We fight together to restore the lantern. Then we can return to Niran and board the ferry.": "/bangkok/voices/line-5bdc07d6159241a6.mp3",
  "Arun|A good traveller asks the price before agreeing to buy. Try asking me how much it is.": "/bangkok/voices/line-5e4ef9ac175ffe52.mp3",
  "Niran|“Mali brings supper to this pier. Arun repairs my lamps. I keep saying we should sit down together, but somehow there is always another crossing.” Niran coils the mooring rope. “You got us across the river. Could you help me keep one small promise?” He can finish early tonight, or take tomorrow morning off. Tell him when you are free.": "/bangkok/voices/line-5f9509bbc4451044.mp3",
  "Arun|“Bamboo,” he says, bending a spare strip to show you. “Light enough for that little hanging shade.”": "/bangkok/voices/line-60925aa47b0e4c3f.mp3",
  "Su|We need a lantern spark, and Niran needs his supper before he can show us the ritual. Check the journal for our next step.": "/bangkok/voices/line-620a993381dc404b.mp3",
  "Su|“Pim has a place beside the lake,” Su says. “A drink and a quieter path sound good.”": "/bangkok/voices/line-645bed21dad1b2ae.mp3",
  "Su|You try the farewell. Niran holds the boat steady while you and Su step aboard.": "/bangkok/voices/line-65cd21728a4d4356.mp3",
  "Mali|Another traveller from the rift! You look exhausted. Before we sort out your room, a greeting would be nice.": "/bangkok/voices/line-667c1a64e626ae03.mp3",
  "Su|The collection belongs to the neighbourhood. Kanya is at reception. Let us ask her permission before handling the records.": "/bangkok/voices/line-678a95bc55e36d5b.mp3",
  "Mali|Mali smiles and returns your greeting. The room feels a little less strange.": "/bangkok/voices/line-688d2c323cbbeb0f.mp3",
  "Su|You ask for no chilli. The stallholder nods and wraps two rice parcels for the road. The recipe board gains another small note: a meal is a conversation, too.": "/bangkok/voices/line-692981a1efd8cee8.mp3",
  "Niran|“Find the wisp in Lumphini. Take its spark to the lantern court in Old Town.” Now you have the plan.": "/bangkok/voices/line-6b274ec226185bd6.mp3",
  "Arun|“For you? Help me carry its story to the river. I’ll give you 15 coins for the errand.”": "/bangkok/voices/line-6b78e5f736a4b475.mp3",
  "Su|Compare your three clues at the map cabinet. Which collection records the lantern delivery? Look around, open your map, or talk to people again. If you want to rehearse a phrase, we can train at camp.": "/bangkok/voices/line-6bbac1954719f658.mp3",
  "Su|You chose a little chilli in Yaowarat. Su remembers the first taste, your surprised laugh, and Lek passing over the water.": "/bangkok/voices/line-6d2f70f200456d73.mp3",
  "Arun|“Thirty coins for the carved lantern.” Arun leaves it on the bench while you decide. You can accept, politely ask for a lower price, or explain that it is too expensive.": "/bangkok/voices/line-7185d31a0293b2f6.mp3",
  "Su|Meet the boat tender at the loading steps on the near quay.": "/bangkok/voices/line-73c953dd03005d7d.mp3",
  "Su|“We have spent the whole day doing what the city needs,” Su says. “What would you like?” Mali suggests Lek’s food stalls or a drink with Pim beside the lake. Tell Su what sounds good. Both replies are welcome.": "/bangkok/voices/line-74df9f6b5092866e.mp3",
  "Pim|Pim takes a seat beside the pavilion. “You remembered the way back. A drink for the next part of your walk?”": "/bangkok/voices/line-74f34a2cf69ae4c2.mp3",
  "Uncle Lek|Take this supper to the pier. These two rice parcels are for you and Su—use them if the spirits wear you down. A wisp has been troubling people in Lumphini Park. You will find it beside the lake.": "/bangkok/voices/line-75bb25c0b0edab1c.mp3",
  "Pim|Ask for water. Simple needs are useful words to have ready before you travel.": "/bangkok/voices/line-760ff40060b5d059.mp3",
  "Su|Everyone has agreed. Meet your friends at Lek’s stall in Yaowarat. Look around, open your map, or talk to people again. If you want to rehearse a phrase, we can train at camp.": "/bangkok/voices/line-766322d77d352d46.mp3",
  "Niran|Your seats are waiting. Find the spark in Lumphini Park, then take it to the Old Town lantern court. Every district has a story worth hearing.": "/bangkok/voices/line-76d2eb9d07fc8b7e.mp3",
  "Su|Visit the workshop, stop for supper, and arrange a meeting by the river.": "/bangkok/voices/line-78d71aeb66e9ec1d.mp3",
  "Arun|Arun unfolds a warm paper shade. “This little one will hold the light.”": "/bangkok/voices/line-791b05d3dc83f6a3.mp3",
  "Dao|I explained that too quickly, didn’t I? Ask me to repeat it.": "/bangkok/voices/line-7a04b5d8e8ed7f93.mp3",
  "Su|Niran gave us a sealed letter for Suda. The landing notice says she lives beyond the canal, at the blue-shutter house beside the tamarind tree. There are two footbridges. We should read the route before setting off.": "/bangkok/voices/line-7aaffbcae00a0590.mp3",
  "Su|A rubbing of the maker’s seal matches the mark on the cargo record. Under it: “The ferryman carried our neighbourhood’s first lanterns.”": "/bangkok/voices/line-7bfb71cf2f45b5c1.mp3",
  "Su|A room, a meal, a favour, a passage across the river. You did all that with a handful of words. Imagine what you will do with a month of them.": "/bangkok/voices/line-7c338af32fd7dae6.mp3",
  "Su|Take a food stop, a quiet park break, and a conversation about the way back.": "/bangkok/voices/line-80d7171609f08e53.mp3",
  "Su|The parcel contained folded paper shades and bamboo frames. The sender wrote: “Keep them dry. These are for the lamps along the water.”": "/bangkok/voices/line-8256bf6bc02ef076.mp3",
  "Pim|Pim reaches for the water jug. “Good after a long walk.”": "/bangkok/voices/line-827a34a3bffc4a4a.mp3",
  "Pim|“I thought you might be.” Pim reaches into her basket.": "/bangkok/voices/line-833c5e7cd4fb856b.mp3",
  "Suda|A letter from Niran? You found the right house. Come to the veranda. Please greet me before you hand it over.": "/bangkok/voices/line-85711b51dc0f30a7.mp3",
  "Uncle Lek|A long wait makes a man thirsty. Ask for some water too.": "/bangkok/voices/line-85b4878c2221fbfa.mp3",
  "Su|Explore the reading room and both galleries. 0 of 3 clues recorded; the rooms connect around a shaded courtyard. Look around, open your map, or talk to people again. If you want to rehearse a phrase, we can train at camp.": "/bangkok/voices/line-88d93c1558c333a7.mp3",
  "Su|Mali asks Arun whether a lantern like this could hang above the hotel desk. He sketches one on a napkin. Niran stops checking the river. Su nudges your shoulder. “You did not need perfect sentences. You needed a time, a place, and the courage to ask.” When the bowls are empty, say “See you again.” This time it feels like a promise you can keep.": "/bangkok/voices/line-89d55d5c36c4979f.mp3",
  "Su|You are awake. This is your hotel on Sukhumvit, Patrick. Beyond the window is Bangkok—and something strange is stealing its words. I am Su. We can work this out together.": "/bangkok/voices/line-8a49f39e6bd83f4a.mp3",
  "Arun|“A repair for the neighbourhood? No charge.” He wraps the frame. “Pim always kept that lamp going. I am glad she has help.”": "/bangkok/voices/line-8cc7f0d5db24129a.mp3",
  "Su|Ask before buying, choose a meal that suits you, then unwind with Pim in the park.": "/bangkok/voices/line-8cf5a6dbdd3e9ec7.mp3",
  "Su|You identified the ferry ledger. Return to Kanya and ask permission to see the original. Look around, open your map, or talk to people again. If you want to rehearse a phrase, we can train at camp.": "/bangkok/voices/line-8e21e6ae862d2c1f.mp3",
  "Su|Lek sets the chilli aside. “There. You should taste the food, not just the fire.” Su leans across the counter. “When we first met, every word felt like a test. This one just bought us an evening.” Tell Lek you enjoyed it.": "/bangkok/voices/line-8f53b75f0b9c35bf.mp3",
  "Su|A damaged lantern stands beside the canal. Visit it to begin an optional errand.": "/bangkok/voices/line-90a8702f9d670285.mp3",
  "Su|Take the supper to Niran at the Chao Phraya pier. Look around, open your map, or talk to people again. If you want to rehearse a phrase, we can train at camp.": "/bangkok/voices/line-912ed955a57a5984.mp3",
  "Mali|“Patrick. I will remember.” She turns the guest book towards you.": "/bangkok/voices/line-9466cbfd809203f6.mp3",
  "Su|Mali suggests a simple challenge: get ready, find your route, and order your own breakfast.": "/bangkok/voices/line-953bc6a1f9ee341d.mp3",
  "Uncle Lek|Lek ties a knot in the supper parcel. “Niran is waiting at the river. These smaller parcels are for your own journey.”": "/bangkok/voices/line-95a2279610d34830.mp3",
  "Su|A guest has left a journal for the next traveller. The first page says: “I spent my first morning afraid to speak. By evening, the noodle seller knew my name.” There is space beneath it for yours.": "/bangkok/voices/line-9748e2c1c49dcb5a.mp3",
  "Arun|Arun sets his tools aside. “Lumphini tomorrow? Gladly. I owe Pim a visit.” He draws a little pavilion on a scrap of wrapping paper. Ask where you should meet so everyone goes to the same place.": "/bangkok/voices/line-98383eb976295b9e.mp3",
  "Uncle Lek|A bottle joins the parcel. One small conversation, one real favour.": "/bangkok/voices/line-9b95a5b800935eef.mp3",
  "Pim|The strange light beside the lake arrived with the mist. Be careful, and come back to rest whenever the city feels too loud.": "/bangkok/voices/line-9bd8ea9ad9c85af9.mp3",
  "Su|The boat stops, but this is not a delivery quay. Look for the red, blue or green pennant.": "/bangkok/voices/line-9bd8edb9a0761774.mp3",
  "Su|Take the spark to the Old Town lantern court. Face the Keeper. Look around, open your map, or talk to people again. If you want to rehearse a phrase, we can train at camp.": "/bangkok/voices/line-9ed2fb4591df70cd.mp3",
  "Su|Everyone has agreed. Meet your friends at Pim’s pavilion in Lumphini. The story moves to the next morning when you arrive; there is no real-time wait. Look around, open your map, or talk to people again. If you want to rehearse a phrase, we can train at camp.": "/bangkok/voices/line-a0c20312e357c46b.mp3",
  "Su|Pim keeps spare paper for the park signs. Arun makes lantern frames in Old Town. We could ask them for the two pieces, in either order, and bring them back here. A small favour can connect a whole neighbourhood.": "/bangkok/voices/line-a1b162b99f2809ef.mp3",
  "Su|The arrows on this waystone keep turning. A guardian of lost travelers is caught inside. Check in at the hotel, then ask Dao by the Sukhumvit train about finding your way. We can return when we are ready.": "/bangkok/voices/line-a25448da1abd40ca.mp3",
  "Nok|“I took a wrong turn after the park. I can see the train above the shops, but every soi looks different from down here.” Nok adjusts a bright orange backpack. Su suggests walking to Dao, the station guide, together.": "/bangkok/voices/line-a2c979e24dff79b4.mp3",
  "Pim|Pim fills a flask and checks that the lid is tight. One tea added to your bag.": "/bangkok/voices/line-a2f002aa2ac77f0f.mp3",
  "Su|The bow turns left. Check where it points before asking to go straight.": "/bangkok/voices/line-a35331773585789b.mp3",
  "Pim|Pim offers water, and packs a flask of tea for later.": "/bangkok/voices/line-a41abb4b4d1cf1c2.mp3",
  "Niran|There it is—the river is shining again! Come aboard, Patrick. You and Su have earned a place on the last ferry.": "/bangkok/voices/line-a8598abbbc43ec8b.mp3",
  "Su|You confirm that you understand. Now find the house by its shutters and the tree; there is no need to knock at every door.": "/bangkok/voices/line-a912faf19b38624e.mp3",
  "Su|Deliver Niran’s letter to Suda first. Then help the neighbours with their canal garden.": "/bangkok/voices/line-aa9779e4237cfdcf.mp3",
  "Su|You chose a mild meal in Yaowarat. Su remembers Lek setting the chilli aside and making room for two new regulars.": "/bangkok/voices/line-aab9ec878f50de61.mp3",
  "Su|Walk to Yaowarat. Find Uncle Lek and order supper for Niran. Look around, open your map, or talk to people again. If you want to rehearse a phrase, we can train at camp.": "/bangkok/voices/line-abbd680b2a9b0816.mp3",
  "Nok|“I thought I would have to find my way alone.” Su nods toward Dao. Thank the guide for helping you both.": "/bangkok/voices/line-acbc1cf61e5065db.mp3",
  "Dao|Here is a pass for your journeys with Su. Thank me, then try your city map. You can still walk everywhere.": "/bangkok/voices/line-b032be5157257de7.mp3",
  "Su|The river is clear. Return to Niran and catch the last ferry. Look around, open your map, or talk to people again. If you want to rehearse a phrase, we can train at camp.": "/bangkok/voices/line-b094c4f55dda5559.mp3",
  "Arun|Every lantern starts as a fragile frame. Choose that one so I can show you how it opens.": "/bangkok/voices/line-b2f6a77be999cc1e.mp3",
  "Pim|The story moves to the next morning. Mali arrives after her shift; Arun has remembered the cups. Niran sits down with the strange expression of someone who is not due anywhere. Pim opens her basket. “For once, nobody is in a hurry.” Ask for water while everyone settles beside the pavilion.": "/bangkok/voices/line-b4a7dcec70b35db2.mp3",
  "Dao|Welcome to Sukhumvit. The trains run above the street, and the sois lead to small surprises. Before a trip, it helps to know how to get someone’s attention.": "/bangkok/voices/line-b5d45f148f2e22b5.mp3",
  "Su|That way reaches a quay or the floating planters. The tender stays here. Turn the bow toward an open channel, then go straight.": "/bangkok/voices/line-b6feb3d096434580.mp3",
  "Su|Revisit the people who helped you. Ask, clarify, and make plans for the next time you meet.": "/bangkok/voices/line-b71ece8e663236fa.mp3",
  "Su|A Light for Late Walkers · You brought the neighbourhood together. Receive 80 XP, 25 coins, a rice parcel and a flask of tea. The lantern will stay lit when we return.": "/bangkok/voices/line-b7557bcc36e85166.mp3",
  "Dao|Dao turns towards you. A polite opening makes asking for help easier.": "/bangkok/voices/line-b7ee5101b3532f17.mp3",
  "Pim|Pim waves as you set off. A small kindness to carry with you.": "/bangkok/voices/line-b80f30a1dd0015a1.mp3",
  "Nok|Su suggests checking in with Mali at your hotel before offering to walk with Nok.": "/bangkok/voices/line-b891ec490cbed87b.mp3",
  "Su|The words you learned at the hotel can reach it. Patrick and I take turns: choose a word art, read what it means in English, then try the Thai aloud. We can inspect the enemy’s plan before committing. Speaking has no time limit.": "/bangkok/voices/line-ba28ec919509a697.mp3",
  "Su|Check in with Mali at your Sukhumvit hotel. Look around, open your map, or talk to people again. If you want to rehearse a phrase, we can train at camp.": "/bangkok/voices/line-bd1b95f4105704d5.mp3",
  "Su|If directions come too quickly, you can ask to hear them again. Try that now, and I will read the notice once more.": "/bangkok/voices/line-bdd2459c5c35dea3.mp3",
  "Su|Help the boat tender deliver flowers to the coloured quays in any order. 1 of 3 trays delivered. Look around, open your map, or talk to people again. If you want to rehearse a phrase, we can train at camp.": "/bangkok/voices/line-be6dec1591e81aca.mp3",
  "Su|A new page for our explorer’s journal. You found 1 of 6 city memories. Find all six to earn the River Charm: it restores 15 HP after each story battle victory.": "/bangkok/voices/line-c00c059520c305eb.mp3",
  "Arun|“This paper lantern is eighteen coins. Same light, simpler frame.” Arun puts it beside the carved one. Take the simpler lantern, ask the carved lantern’s price again, or think it over and return later.": "/bangkok/voices/line-c105fb5dc7098c0c.mp3",
  "Mali|Rest here whenever you need. That key also opens the luggage chest beside reception. Su saw the missing ferry spark drifting in Lumphini Park. Face the spirit together, then visit Uncle Lek in Yaowarat for our stranded ferryman’s supper.": "/bangkok/voices/line-c17e5fbde1b0c513.mp3",
  "Su|The labels name three collections: road surveys, lantern patterns, and ferry deliveries. We need the cargo record, river photograph and maker’s rubbing before deciding. There is a room on each side of the courtyard.": "/bangkok/voices/line-c1bde6000b765f9e.mp3",
  "Su|The return ferry is ready. Say goodbye to the canal quarter; we can visit again.": "/bangkok/voices/line-c1c7465017b9874a.mp3",
  "Su|Lek adds just a little chilli. The first taste makes you both reach for the water, laughing. Su leans across the counter. “When we first met, every word felt like a test. This one just bought us an evening.” Tell Lek you enjoyed it.": "/bangkok/voices/line-c1d003fe52608f45.mp3",
  "Su|The brass key turns! Inside: a Jade Ward, 25 coins, and a flask of Thai tea. The ward reduces incoming damage by 3. A little exploring pays off.": "/bangkok/voices/line-c2e3e72dd0037f71.mp3",
  "Su|First, meet Mali at reception. Our room is the start of a much bigger journey. Walk with WASD or the arrow keys, or click the ground. Talk with E. The little map can guide you around obstacles.": "/bangkok/voices/line-c3175c31b6aac110.mp3",
  "Su|You brought Mali, Arun and Niran together beside the Lumphini pavilion the next morning. Niran promised to take Mali on the ferry on her day off. Your words made a new plan possible. Look around, open your map, or talk to people again. If you want to rehearse a phrase, we can train at camp.": "/bangkok/voices/line-c52177fd55846f75.mp3",
  "Dao|“Explore on foot first. Then your city pass can bring you back to a familiar district.”": "/bangkok/voices/line-c57f4d9b60b683a3.mp3",
  "Su|A Way Back Together · You helped Nok reach the station. Receive 70 XP, 20 coins and a flask of tea. Nok will be here when you return.": "/bangkok/voices/line-c604e41d78505a62.mp3",
  "Su|You chose water beside the Lumphini lake. Su remembers a quiet conversation that had nothing to do with saving the city.": "/bangkok/voices/line-c71d01c9303b2e2f.mp3",
  "Arun|The bamboo frame fits the canal lamp. Tell Arun you will take this one.": "/bangkok/voices/line-c759a23d8454c879.mp3",
  "Pim|Pim lifts the tea flask you pointed to. “This one? Of course.”": "/bangkok/voices/line-c87ea17be2628553.mp3",
  "Dao|“Come back whenever you need directions,” Dao says. Nok leaves you a flask of tea for your next walk.": "/bangkok/voices/line-c8e75c573d4cb34e.mp3",
  "Su|You and Su step aboard for the city pier.": "/bangkok/voices/line-ca057be15bf12755.mp3",
  "Su|All three quays are planted. You used directions to bring the neighbours together, and the flowers will be here when we return. Take these supplies for our next adventure.": "/bangkok/voices/line-ca4bb2d435dfcbcd.mp3",
  "Su|Beyond Old Town’s east gate, meet Kanya and ask to explore her community archive. Look around, open your map, or talk to people again. If you want to rehearse a phrase, we can train at camp.": "/bangkok/voices/line-cd7493ccc78496c2.mp3",
  "Uncle Lek|Lek wraps a warm parcel for the road. One rice parcel added to your bag.": "/bangkok/voices/line-ce541bb1c564ee6c.mp3",
  "Pim|“The little lamp by the canal? I wondered who would notice.” Pim starts explaining the folds too quickly. Ask her to speak slowly so you can follow.": "/bangkok/voices/line-d25cef9928e7f9ab.mp3",
  "Su|Suda has the letter. The garden boat on the near quay needs a guide for its flower deliveries. We can help, explore the second footbridge, or return to the ferry.": "/bangkok/voices/line-d40694e4e78751be.mp3",
  "Su|Explore the reading room and both galleries. 2 of 3 clues recorded; the rooms connect around a shaded courtyard. Look around, open your map, or talk to people again. If you want to rehearse a phrase, we can train at camp.": "/bangkok/voices/line-d7527eb2a6a9cf54.mp3",
  "Su|The light here is steady now. We made a difference.": "/bangkok/voices/line-d7ae62a0d92cfbb5.mp3",
  "Su|When the spirit answers, choose steady guard or try a timed dodge or parry. Our rice and tea come from the bag we carry through the city. If we need to retreat, we can rest with Mali and return. Ready?": "/bangkok/voices/line-dbe6b1126be8a058.mp3",
  "Su|Locked. A brass key might fit. Let us ask someone at the inn.": "/bangkok/voices/line-dccac5df8d82a13b.mp3",
  "Su|The canal lantern has a torn shade and a bent frame. Under it, a little note reads: “For anyone walking home after dark.” Someone has been looking after this path.": "/bangkok/voices/line-de99b21cdedf696b.mp3",
  "Su|A woven basket rests beside the lakeside path. Pim’s note reads: “For anyone who walked further than they planned. Please take a drink.” The city sounds softer here. Su asks how you would request water.": "/bangkok/voices/line-e1fa1e4b73e3d6fb.mp3",
  "Kanya|“We have lost the catalogue entry for our first lantern delivery. Look at the cargo record in the reading room, the photograph in the river gallery, and the rubbing in the lantern gallery. Compare them at the map cabinet. The galleries join around the courtyard; either direction will take you through.”": "/bangkok/voices/line-e317ad2764cf8874.mp3",
  "Arun|Arun is fitting a new handle to an old lantern. “A meal with Niran and Mali? Yes. But Yaowarat has a lot of stalls.” He knows Lek’s corner and offers to explain the exact meeting point. Ask where you should meet.": "/bangkok/voices/line-e66c2569eab1e5e7.mp3",
  "Uncle Lek|“Tonight you are eating here, not carrying supper for someone else!” Lek puts two bowls on the counter. He holds up the chilli jar and waits for your preference. Su lets you do the talking.": "/bangkok/voices/line-e68d68e1187b3268.mp3",
  "Arun|The tall lantern in this court is different. If you find a spark in Lumphini, it may wake again.": "/bangkok/voices/line-e7aa0fda14439f27.mp3",
  "Su|Pim pours cool water into two cups. Su watches the small ripples. “I kept thinking we had to hurry. I had forgotten we could choose to stop.” Thank Pim for making you welcome.": "/bangkok/voices/line-e7f42741625bf647.mp3",
  "Arun|Arun sets a heavy metal frame beside a lighter one. Before you choose, ask what the lighter frame is made of.": "/bangkok/voices/line-e8452043d54d9b2a.mp3",
  "Uncle Lek|Niran has been waiting at the pier all evening. Help me put his supper together. Point to this bowl and say you would like it.": "/bangkok/voices/line-ebe43c9e1f577df2.mp3",
  "Suda|Thank you for finding me. Take this tea for your return journey. The other bridge makes a loop back to the landing, so you can see the rest of our canal walk.": "/bangkok/voices/line-eef3c0e5dde0beba.mp3",
  "Su|That spirit feeds on uncertainty. Let us learn a greeting at the inn before we face it.": "/bangkok/voices/line-ef4aebe4bc0de700.mp3",
  "Su|Mali admits she has never ridden Niran’s ferry just for the view. “Your next day off,” he says, “the first seat is yours.” Arun laughs: “I am a witness.” Su watches the three of them. “Yesterday you were finding your way through this city. Today you helped them find each other.” Say “See you again” before you leave the pavilion.": "/bangkok/voices/line-ef7c2fc27d18a58d.mp3",
  "Su|A damaged lantern waits beside the canal. Let us check in with Mali at the hotel first, then come back to see whether we can help.": "/bangkok/voices/line-ef8833afb155c22e.mp3",
  "Niran|Niran folds the pass into your hand. “I will keep two seats.”": "/bangkok/voices/line-f016bf6b87a94c72.mp3",
  "Su|Both pieces are in your bag. Return to the canal lantern and help Su fit them together.": "/bangkok/voices/line-f25a544901e3b481.mp3",
  "Su|Kanya has shared the ledger. Thank her for her time to finish your visit. Look around, open your map, or talk to people again. If you want to rehearse a phrase, we can train at camp.": "/bangkok/voices/line-f2a10f5cd30c6c48.mp3",
  "Mali|I am Mali. What should I call you?": "/bangkok/voices/line-f44f478c27b82bb5.mp3",
  "Su|The last ferry leaves at moonrise. Its lantern has gone dark. We need a spark, a little courage, and a few words people can understand.": "/bangkok/voices/line-f48203798cf79041.mp3",
  "Kanya|“Welcome. These rooms hold the stories our neighbours gave us.” Kanya sets down her pencil. “You are welcome to look around. Ask me before entering the galleries, and I will tell you what we are trying to find.”": "/bangkok/voices/line-f5dfaf5caecd52d9.mp3",
  "Dao|Return journeys are now available to districts you have visited. “There is also a brass waystone on the road to Yaowarat,” Dao adds. “Its guardian rewards travelers who work together. Look for it on your map when you feel ready.”": "/bangkok/voices/line-f77a858f8844d77f.mp3",
  "Su|Travel to Lumphini with Su. Defeat the Murmur to recover the ferry’s lantern spark. Look around, open your map, or talk to people again. If you want to rehearse a phrase, we can train at camp.": "/bangkok/voices/line-f915a7e2db44dcef.mp3",
  "Su|Finish or pause your current activity before guiding the garden boat.": "/bangkok/voices/line-f932898ed358294b.mp3",
  "Su|A new page for our explorer’s journal. You found 4 of 6 city memories. Find all six to earn the River Charm: it restores 15 HP after each story battle victory.": "/bangkok/voices/line-f93c4b112da662a4.mp3",
  "Su|A narrow boat waits beside the old pier. The caption says the delivery left after the food stalls closed. No road or railway carried it.": "/bangkok/voices/line-fa528c4039b8b333.mp3",
  "Su|Collect paper from Pim in Lumphini. Visit them in either order, then return to the canal lantern.": "/bangkok/voices/line-fa595fe10d477184.mp3",
  "Uncle Lek|Mali reaches the stall without her desk bell. Arun puts the repaired lantern between the bowls. Niran arrives last, still carrying his ferry cap. “You did it,” Lek says. “Usually I feed these three separately.” He points to the empty cups. Ask for water while he brings the food.": "/bangkok/voices/line-fa82446f832db6eb.mp3",
  "Uncle Lek|The chilli jar goes back on the shelf. Lek gives you an approving nod.": "/bangkok/voices/line-fabe80a3b44f8625.mp3",
  "Su|Paper shades and bamboo frames. A boat after the stalls closed. The maker’s seal and a ferryman. Use all three clues to choose the collection that records the journey, then ask Kanya for the original.": "/bangkok/voices/line-fe3038a71fd7c68e.mp3",
  "Pim|“Bring its light back, and we will both have helped someone get home.” The paper shade is ready to carry.": "/bangkok/voices/line-fe794a890745819a.mp3",
  "Kanya|Kanya has added your names beside the ferry ledger. “You followed the small details. That is how a city remembers.” You can wander the galleries whenever you return.": "/bangkok/voices/line-ff21acbc5af5b90b.mp3",
  "Su|ถูกกว่านี้ได้ไหมครับ": "/bangkok/voices/little-cheaper.mp3",
  "Su|เผ็ดนิดหน่อยครับ": "/bangkok/voices/little-spicy.mp3",
  "Su|ผมกำลังหาข้อมูลครับ": "/bangkok/voices/looking-for-info.mp3",
  "Su|ขอสอบถามหน่อยครับ": "/bangkok/voices/may-ask.mp3",
  "Su|ขอเข้าไปได้ไหมครับ": "/bangkok/voices/may-enter.mp3",
  "Su|ขอดูเอกสารได้ไหมครับ": "/bangkok/voices/may-see-document.mp3",
  "Su|เจอกันที่ไหนครับ": "/bangkok/voices/meet-where.mp3",
  "Su|ผมชื่อแพทริกครับ": "/bangkok/voices/my-name-is-patrick.mp3",
  "Su|อยู่ใกล้ไหมครับ": "/bangkok/voices/near-here.mp3",
  "Su|ผมต้องไปโรงพยาบาลครับ": "/bangkok/voices/need-hospital.mp3",
  "Su|ต้องกินยาอะไรครับ": "/bangkok/voices/need-medicine.mp3",
  "Su|ขั้นตอนต่อไปคืออะไรครับ": "/bangkok/voices/next-step.mp3",
  "Su|ยินดีที่ได้รู้จักครับ": "/bangkok/voices/nice-to-meet-you.mp3",
  "Su|ไม่ใช่ครับ": "/bangkok/voices/no.mp3",
  "Su|ไม่เอาถั่วครับ": "/bangkok/voices/no-peanuts.mp3",
  "Su|ผมไม่ค่อยชอบเผ็ดครับ": "/bangkok/voices/not-like-spicy.mp3",
  "Su|ไม่เผ็ดครับ": "/bangkok/voices/not-spicy.mp3",
  "Su|วันนี้ยังไม่เอาครับ": "/bangkok/voices/not-today.mp3",
  "Su|ขอหนึ่งจานครับ": "/bangkok/voices/one-plate.mp3",
  "Su|โทรศัพท์แบตหมดครับ": "/bangkok/voices/phone-dead.mp3",
  "Su|ช่วยผมด้วยครับ": "/bangkok/voices/please-help.mp3",
  "Su|จองไว้ครับ": "/bangkok/voices/reservation-have.mp3",
  "Su|พูดอีกครั้งได้ไหมครับ": "/bangkok/voices/say-again.mp3",
  "Su|แล้วเจอกันครับ": "/bangkok/voices/see-you.mp3",
  "Su|มีผลข้างเคียงไหมครับ": "/bangkok/voices/side-effects.mp3",
  "Su|ขอโทษครับ": "/bangkok/voices/sorry.mp3",
  "Su|ช่วยพูดช้าลงหน่อยครับ": "/bangkok/voices/speak-slowly.mp3",
  "Su|ปวดท้องครับ": "/bangkok/voices/stomach-hurts.mp3",
  "Su|จอดตรงนี้ครับ": "/bangkok/voices/stop-here.mp3",
  "Su|ขอบคุณที่สละเวลาครับ": "/bangkok/voices/thank-for-time.mp3",
  "Su|ขอบคุณครับ": "/bangkok/voices/thank-you.mp3",
  "Su|ขอคิดดูก่อนครับ": "/bangkok/voices/think-first.mp3",
  "Su|พรุ่งนี้ได้ไหมครับ": "/bangkok/voices/tomorrow-ok.mp3",
  "Su|แพงไปครับ": "/bangkok/voices/too-expensive.mp3",
  "Su|รถติดไหมครับ": "/bangkok/voices/traffic-heavy.mp3",
  "Su|เลี้ยวซ้ายครับ": "/bangkok/voices/turn-left.mp3",
  "Su|เลี้ยวซ้ายหรือขวาครับ": "/bangkok/voices/turn-left-right.mp3",
  "Su|เลี้ยวขวาครับ": "/bangkok/voices/turn-right.mp3",
  "Su|ชื่อแพทริกครับ": "/bangkok/voices/under-name.mp3",
  "Su|รับทราบครับ": "/bangkok/voices/understand-formal.mp3",
  "Su|เปิดมิเตอร์ได้ไหมครับ": "/bangkok/voices/use-meter.mp3",
  "Su|เอาอันนี้ครับ": "/bangkok/voices/want-this.mp3",
  "Su|ขอน้ำเปล่าครับ": "/bangkok/voices/water-please.mp3",
  "Su|อันนี้คืออะไรครับ": "/bangkok/voices/what-is-this.mp3",
  "Su|ทำจากอะไรครับ": "/bangkok/voices/what-material.mp3",
  "Su|สถานีอยู่ที่ไหนครับ": "/bangkok/voices/where-is-station.mp3",
  "Su|ห้องผมอยู่ชั้นไหนครับ": "/bangkok/voices/which-floor.mp3",
  "Su|ใช่ครับ": "/bangkok/voices/yes.mp3"
};
