import { journeyHosts, type JourneyActor } from './cityJourneys.ts';

/** English situations give existing Thai phrases a purpose without inventing new translations. */
export const journeySituations: Record<string, string> = {
  hello: 'You have just arrived. Open the conversation politely.',
  'my-name-is-patrick': 'Mali asks who she is speaking with. Introduce yourself.',
  'reservation-have': 'At reception, explain that you already made a booking.',
  'under-name': 'Mali is checking the booking list. Tell her whose name to look for.',
  'check-in-please': 'You have reached the hotel after your journey. Ask to check in.',
  'key-where': 'You are ready to go upstairs, but need your room key. Ask where it is.',
  'which-floor': 'You have your room number. Find out which floor to go to.',
  'elevator-where': 'You are carrying your bag. Ask where to find the lift.',
  'speak-slowly': '{host} is speaking faster than you can follow. Ask for a slower pace.',
  'say-again': 'You missed part of what {host} said. Ask to hear it again.',
  'thank-you': '{host} has helped you. Acknowledge their help before continuing.',
  'bathroom-where': 'Before carrying on with your day, ask where the bathroom is.',
  sorry: 'You need to interrupt {host} politely before asking a question.',
  'where-is-station': 'You are planning your next journey. Ask where the station is.',
  'near-here': 'Before deciding to walk, check whether the place is nearby.',
  'go-how': 'You know the destination but not the route. Ask how to get there.',
  'turn-left-right': 'Check the directions by saying the two turns back to Dao: left, then right.',
  'i-am-lost': 'The route no longer looks familiar. Explain the problem to Dao.',
  'please-help': 'You are unsure what to do next. Ask {host} for help.',
  'want-this': 'Point to the dish you would like so Lek knows your choice.',
  'one-plate': 'Lek is ready to take your order. Ask for a single serving.',
  'not-spicy': 'Before Lek prepares the food, ask for it without chilli heat.',
  'little-spicy': 'You would like some chilli heat, but only a little. Tell Lek before cooking.',
  'water-please': 'You would like water with your break. Make the request politely.',
  'bill-please': 'You have finished eating and are ready to pay. Ask Lek for the bill.',
  delicious: 'You enjoyed the food. Tell Lek what you thought of it.',
  'like-thai-food': 'Lek asks about your food preferences. Tell him you enjoy Thai food.',
  'not-like-spicy': 'You are discussing your usual tastes. Explain that you do not like spicy food.',
  'how-much': 'Before deciding whether to buy, ask {host} the price.',
  'i-am-thirsty': 'After walking through the park, tell Pim why you need a drink.',
  'nice-to-meet-you': 'Pim has introduced herself. Respond warmly to your first meeting.',
  'what-is-this': 'An unfamiliar object catches your eye in the workshop. Ask Arun what it is.',
  'what-material': 'You are considering a souvenir. Ask Arun what it is made from.',
  'too-expensive': 'The quoted price is beyond your budget. Explain that it is too expensive.',
  'little-cheaper': 'You like the item. Politely ask Arun whether the price can be lower.',
  'think-first': 'You are interested but not ready to decide. Ask for time to think.',
  'not-today': 'You have decided to leave without buying. Decline politely.',
  'i-will-buy': 'You have made your choice. Tell Arun that you will take this item.',
  'has-color': 'The sample is not the colour you want. Ask whether another colour is available.',
  'buy-two': 'You want one souvenir for yourself and one as a gift. Tell Arun you want two.',
  'how-long': 'You need to plan your afternoon. Ask Niran how long the journey takes.',
  'how-much-to-go': 'Before agreeing to the journey, ask Niran how much it costs to go.',
  'meet-where': 'You are arranging to meet again. Check the meeting place with Niran.',
  'tomorrow-ok': 'Your plans need another day. Ask Niran whether tomorrow works.',
  'go-together': 'You would like company for the journey. Suggest going together.',
  'see-you': 'The river conversation is ending. Say goodbye with the expectation of meeting again.',
};
export function journeySituation(actor: JourneyActor, phrase: string): string {
  return (journeySituations[phrase] ?? journeyHosts[actor].scene).replaceAll(
    '{host}',
    journeyHosts[actor].name,
  );
}
